// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(NewDbContext))]
    [Migration("20251127094230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Departments", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentManagerNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentCode");

                    b.HasIndex("DepartmentManagerNum");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusFlag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode");

                    b.HasIndex("ManagerNum");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProjectAssignTable", b =>
                {
                    b.Property<string>("AssignId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BillRate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HrsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignId");

                    b.HasIndex("EmployeeNum");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("Departments", b =>
                {
                    b.HasOne("EmployeeData", "Manager")
                        .WithMany()
                        .HasForeignKey("DepartmentManagerNum");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeData", b =>
                {
                    b.HasOne("Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode");

                    b.HasOne("EmployeeData", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerNum");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ProjectAssignTable", b =>
                {
                    b.HasOne("EmployeeData", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeNum");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
